language: python # (Ansible)

install:

  # Install Sphinx
  - pip install --upgrade pip
  - pip install sphinx==1.5.3
  - pip install sphinx-autobuild==0.6.0
  - pip install sphinx_rtd_theme==0.2.4

script:
  - sphinx-build -W -b html -d _build/doctrees   . _build/html
  